
name: Linting workflow

on: [push, pull_request]

jobs:
    lint-backend:
        runs-on: ubuntu-latest
        name: Backend - Lint Check
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Nodejs
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - working-directory: conclave-backend
            - run: npm install
            - run: npm run lint
